/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.9
 * Generated at: 2025-10-17 18:33:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.backigesta.model.Admin;
import com.backigesta.model.Empresas;
import com.backigesta.model.Usuarios;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.backigesta.model.Usuarios");
    _jspx_imports_classes.add("com.backigesta.model.Admin");
    _jspx_imports_classes.add("com.backigesta.model.Empresas");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"IGesta, o seu app de Análise de Dados inteligente\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/style.css\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/logos/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <title>IGesta</title>\r\n");
      out.write("    ");

        Empresas empresa = (Empresas) session.getAttribute("empresa");
        Admin admin = (Admin) session.getAttribute("admin");
    
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <section>\r\n");
      out.write("            <img src=\"assets/logos/logo-branca.png\">\r\n");
      out.write("            <h1>IGesta</h1>\r\n");
      out.write("        </section>\r\n");
      out.write("        <a href=\"mb-header.jsp\"><div><p>≡</p></div></a>\r\n");
      out.write("        <ul class=\"links\">\r\n");
      out.write("            <li><a href=\"#slide01\" class=\"linkAnimation\">Início</a></li>\r\n");
      out.write("            <li><a href=\"#slide06\" class=\"linkAnimation\">Empresa</a></li>\r\n");
      out.write("            <li><a href=\"#slide05\" class=\"linkAnimation\">Mensalidades</a></li>\r\n");
      out.write("            ");
 if (admin == null && empresa == null) { 
      out.write("\r\n");
      out.write("                <li><a id=\"entrar\" onclick=\"opcoesEntrar()\"><button>Entrar</button></a></li>\r\n");
      out.write("            ");
 } else if (admin != null) { 
      out.write("\r\n");
      out.write("                <li><a class=\"conta\" onclick=\"opcoesEntrar()\"><img src=\"");
      out.print( admin.getFoto() == null ? "assets/icons/aside-perfil.svg" : "getFoto?id=" + admin.getId() + "&tipo=Admin");
      out.write('"');
      out.write('>');
      out.print(admin.getNome());
      out.write("</a></li>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <li><a class=\"conta\" onclick=\"opcoesEntrar()\"><img src=\"");
      out.print( empresa.getFoto() == null ? "assets/icons/aside-perfil.svg" : "getFoto?id=" + empresa.getId() + "&tipo=Empresas");
      out.write('"');
      out.write('>');
      out.print(empresa.getNome());
      out.write("</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"overlay\" id=\"popupOverlay\">\r\n");
      out.write("        ");
 if (session.getAttribute("admin") == null && session.getAttribute("empresa") == null) { 
      out.write("\r\n");
      out.write("            <a href=\"loginAdmin\">\r\n");
      out.write("                <div>Entrar como admin</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"loginEmpresa\">\r\n");
      out.write("                <div>Entrar como empresa</div>\r\n");
      out.write("            </a>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            ");
 if (session.getAttribute("admin") != null) { 
      out.write("\r\n");
      out.write("                <a href=\"selectCondena\">\r\n");
      out.write("                    <div>Área restrita</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <a href=\"\">\r\n");
      out.write("                    <div>Ver lideres e gestores</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <a href=\"logout\">\r\n");
      out.write("                <div>Sair</div>\r\n");
      out.write("            </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <div class=\"slides\" id=\"slide01\">\r\n");
      out.write("            <img src=\"assets/images/splash-helmet.png\">\r\n");
      out.write("            <section>\r\n");
      out.write("                <h1>IGesta</h1>\r\n");
      out.write("                <p>Análise de Dados da Indústria</p>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"slides\" id=\"slide02\">\r\n");
      out.write("            <section id=\"phrases\">\r\n");
      out.write("                <h2>INOVAÇÃO</h2>\r\n");
      out.write("                <h2>GESTÃO</h2>\r\n");
      out.write("                <h2>EVOLUÇÃO</h2>\r\n");
      out.write("            </section>\r\n");
      out.write("            <p>IGesta é uma solução inteligente que simplifica processos, automatiza a contagem e transforma dados em análises claras para otimizar a gestão nas indústrias alimentícias.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"slides\" id=\"slide03\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <section class=\"card\">\r\n");
      out.write("                    <h3>Análise de Dados</h3>\r\n");
      out.write("                    <p>Da complexidade dos dados à clareza estratégica</p>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"card\">\r\n");
      out.write("                    <h3>Dashboards</h3>\r\n");
      out.write("                    <p>Transforme dados em decisões</p>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"card\">\r\n");
      out.write("                    <h3>Armazenamento na nuvem</h3>\r\n");
      out.write("                    <p>Guarde hoje, acesse de onde quiser amanhã</p>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"card\">\r\n");
      out.write("                    <h3>Chatbot</h3>\r\n");
      out.write("                    <p>Decisões rápidas começam com respostas rápidas</p>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"slides\" id=\"slide04\">\r\n");
      out.write("            <h2>Nossos objetivos</h2>\r\n");
      out.write("            <img src=\"assets/images/objectives01-pc.png\">\r\n");
      out.write("            <p>Reduzir desperdícios</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"slides\" id=\"slide05\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <h2>Mensalidades</h2>\r\n");
      out.write("                <p>Por armazenamento</p>\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"plano\" value=\"basico\" id=\"plano\">\r\n");
      out.write("                    <button type=\"submit\">Assinar</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <section class=\"card\" onclick=\"deixarSelecionado(4)\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h3>Básico</h3>\r\n");
      out.write("                        <p>3TB</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>R$200</p>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"card\" onclick=\"deixarSelecionado(5)\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h3>Intermediário</h3>\r\n");
      out.write("                        <p>4TB</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>R$300</p>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"card\" onclick=\"deixarSelecionado(6)\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h3>Avançado</h3>\r\n");
      out.write("                        <p>5TB</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>R$400</p>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"slides\" id=\"slide06\">\r\n");
      out.write("            <img src=\"assets/images/team-pc.png\">\r\n");
      out.write("            <section>\r\n");
      out.write("                <h2>Quem somos nós</h2>\r\n");
      out.write("                <p>Somos 14 estudantes da Germinare Tech e unimos nossas ideias para criar um projeto voltado ao ODS 9 (Indústria, Inovação e Infraestrutura). Nosso objetivo é desenvolver um aplicativo que auxilie as indústrias a se modernizarem, crescerem de forma sustentável e se tornarem mais competitivas, impulsionando a inovação e o desenvolvimento tecnológico.</p>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"slides\" id=\"slide07\">\r\n");
      out.write("            <img src=\"assets/images/timeline.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"slides\" id=\"slide08\">\r\n");
      out.write("            <p>A tecnologia que transforma dados em decisões</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("            <section>\r\n");
      out.write("                <h1>IGesta</h1>\r\n");
      out.write("                <p>Tecnologia que transforma<br>Dados em Decisões</p>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <section class=\"links\">\r\n");
      out.write("                <h3>Links</h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#slide01\" class=\"linkAnimation\">Início</a></li>\r\n");
      out.write("                    <li><a href=\"#slide05\" class=\"linkAnimation\">Mensalidades</a></li>\r\n");
      out.write("                    <li><a href=\"htmls/updates.html\" class=\"linkAnimation\">Atualizações</a></li>\r\n");
      out.write("                    <li><a href=\"emailContato\" class=\"linkAnimation\">Contato</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <section>\r\n");
      out.write("                <h3>Conecte-se</h3>\r\n");
      out.write("                <abbr title=\"Facebook\"><a href=\"https://www.facebook.com/profile.php?id=61576575636670\" target=\"_blank\"><img src=\"assets/icons/socialmedia-facebook.png\"></a></abbr>\r\n");
      out.write("                <abbr title=\"Instagram\"><a href=\"https://www.instagram.com/igesta.app/\" target=\"_blank\"><img src=\"assets/icons/socialmedia-instagram.png\"></a></abbr>\r\n");
      out.write("                <abbr title=\"LinkedIn\"><a href=\"https://www.linkedin.com/in/aeu-tech/\" target=\"_blank\"><img src=\"assets/icons/socialmedia-linkedin.png\"></a></abbr>\r\n");
      out.write("                <abbr title=\"YouTube\"><a href=\"https://www.youtube.com/@aeutech\" target=\"_blank\"><img src=\"assets/icons/socialmedia-youtube.png\"></a></abbr>\r\n");
      out.write("            </section>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </main>\r\n");
      out.write("    <script src=\"scripts/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
