/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.9
 * Generated at: 2025-10-17 18:34:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.backigesta.model.Condenas;
import com.backigesta.model.Admin;

public final class condenas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.backigesta.model.Admin");
    _jspx_imports_classes.add("com.backigesta.model.Condenas");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/logos/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/restrict-area.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/popups.css\">\r\n");
      out.write("    <title>Condenas</title>\r\n");
      out.write("    ");

        Admin admin = (Admin) session.getAttribute("admin");
        if (admin == null) {
            response.sendRedirect("index.jsp");
            return;
        }

        List<Condenas> condenas = (List<Condenas>) request.getAttribute("condenas");

        String adicionado = (String) request.getAttribute("adicionado");
        String alterado = (String) request.getAttribute("alterado");
        String deletado = (String) request.getAttribute("deletado");
    
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <aside>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/logos/logo-branca.png\"></a>\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"company.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/icons/aside-company.svg\"></a>\r\n");
      out.write("            <a href=\"condemn.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/icons/aside-condemn.svg\"></a>\r\n");
      out.write("            <a href=\"payment.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/icons/aside-payment.svg\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"entrarPerfil\">\r\n");
      out.write("            ");
if(admin.getFoto()!=null){
      out.write("\r\n");
      out.write("            <img id=\"fotoPerfil\" src=\"getFoto?id=");
      out.print(admin.getId());
      out.write("&tipo=Admin\">\r\n");
      out.write("            ");
} else {
      out.write("\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/icons/aside-perfil.svg\">\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <header>\r\n");
      out.write("            <h1>Condenas</h1>\r\n");
      out.write("            <menu>\r\n");
      out.write("                <form action=\"selectCondena\" method=\"get\">\r\n");
      out.write("                    <input type=\"hidden\" value=\"todos\" name=\"filter\">\r\n");
      out.write("                    <button type=\"submit\" id=\"todos\" class=\"options\">Todas</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <form action=\"selectCondena\" method=\"get\">\r\n");
      out.write("                    <input type=\"hidden\" value=\"total\" name=\"filter\">\r\n");
      out.write("                    <button type=\"submit\" id=\"total\" class=\"options\">Total</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <form action=\"selectCondena\" method=\"get\">\r\n");
      out.write("                    <input type=\"hidden\" value=\"parcial\" name=\"filter\">\r\n");
      out.write("                    <button type=\"submit\" id=\"parcial\" class=\"options\">Parcial</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <form action=\"selectCondena\" id=\"search\">\r\n");
      out.write("                    <input type=\"text\" name=\"search\" placeholder=\"Pesquisar\">\r\n");
      out.write("                    <button type=\"submit\" class=\"functions\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/icons/menu-search.svg\" alt=\"Pesquisar\">\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <button onclick=\"abrirPopup('add')\" class=\"functions\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/icons/menu-add.svg\">\r\n");
      out.write("                </button>\r\n");
      out.write("            </menu>\r\n");
      out.write("        </header>\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"table condemn\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>Nome</li>\r\n");
      out.write("                    <li>Tipo</li>\r\n");
      out.write("                    <li>Descrição</li>\r\n");
      out.write("                    <li>Criador</li>\r\n");
      out.write("                    <li>Ações</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                ");
 for (Condenas condena : condenas) { 
      out.write("\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>");
      out.print(condena.getNome());
      out.write("</li>\r\n");
      out.write("                        <li>");
      out.print(condena.getTipoCondena());
      out.write("</li>\r\n");
      out.write("                        <li>");
      out.print(condena.getDescricao() != null ? condena.getDescricao() : "Sem descricao");
      out.write("</li>\r\n");
      out.write("                        <li>");
      out.print(condena.getNomeAdmin());
      out.write("</li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a onclick=\"alterarCondena(");
      out.print(condena.getId());
      out.write(")\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/icons/edit.svg\"></a>\r\n");
      out.write("                            <input type=\"hidden\" id=\"condenaAlterar");
      out.print(condena.getId());
      out.write("\" value=\"");
      out.print(condena.getNome());
      out.write(';');
      out.print(condena.getTipoCondena());
      out.write(';');
      out.print(condena.getDescricao());
      out.write("\">\r\n");
      out.write("                            <a onclick=\"deletarCondena(");
      out.print(condena.getId());
      out.write(")\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/icons/trash.svg\"></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("    <dialog id=\"add\" class=\"popupInputs\">\r\n");
      out.write("        <h2>Adicionar condena</h2>\r\n");
      out.write("        <form action=\"adicionarCondena\" method=\"post\" autocomplete=\"off\">\r\n");
      out.write("            <a onclick=\"document.getElementById('add').close()\"><img src=\"assets/icons/arrow-left.png\"></a>\r\n");
      out.write("            <input type=\"text\" name=\"nomeCondena\" placeholder=\"Nome\" class=\"inputCapitalize\">\r\n");
      out.write("            <select name=\"tipo\">\r\n");
      out.write("                <option value=\"\" disabled selected >Tipo Condena</option>\r\n");
      out.write("                <option value=\"Total\">Total</option>\r\n");
      out.write("                <option value=\"Parcial\">Parcial</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <textarea name=\"descricaoCondena\" placeholder=\"Mensagem\" required></textarea>\r\n");
      out.write("            <button type=\"submit\">Adicionar</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </dialog>\r\n");
      out.write("    <dialog id=\"delete\" class=\"popupButtons\">\r\n");
      out.write("        <a onclick=\"document.getElementById('delete').close()\"><img src=\"assets/icons/arrow-left.png\"></a>\r\n");
      out.write("        <h2>Excluir condena?</h2>\r\n");
      out.write("        <div>\r\n");
      out.write("            <button onclick=\"document.getElementById('delete').close()\">Não</button>\r\n");
      out.write("            <form action=\"deletarCondena\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" id=\"deletarCondena\" name=\"condenaId\">\r\n");
      out.write("                <button type=\"submit\">Sim</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </dialog>\r\n");
      out.write("    <dialog id=\"alterar\" class=\"popupInputs\">\r\n");
      out.write("        <h2>Alterar condena</h2>\r\n");
      out.write("        <a onclick=\"document.getElementById('alterar').close()\"><img src=\"assets/icons/arrow-left.png\"></a>\r\n");
      out.write("        <form action=\"alterarCondena\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" name=\"condenaId\" id=\"condenaId\">\r\n");
      out.write("            <input type=\"text\" id=\"nomeCondena\" name=\"nomeCondena\" class=\"inputCapitalize\">\r\n");
      out.write("            <select name=\"tipo\" id=\"tipoCondena\"></select>\r\n");
      out.write("            <textarea name=\"descricaoCondena\" id=\"descricaoCondena\" placeholder=\"Mensagem\" required></textarea>\r\n");
      out.write("            <button type=\"submit\">Alterar</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </dialog>\r\n");
      out.write("    <div class=\"overlay\" id=\"popupOverlay\">\r\n");
      out.write("        <div class=\"popup\">\r\n");
      out.write("            <div class=\"icon\">\r\n");
      out.write("                <img id=\"icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/icons/\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <h2 id=\"title\"></h2>\r\n");
      out.write("            <p id=\"text\"></p>\r\n");
      out.write("            <button onclick=\"fecharPopupInformacoes()\">Ok</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/areaRestritaCondenas.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/popupInformacoes.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        ");
 if (adicionado != null) { 
      out.write("\r\n");
      out.write("            ");

                boolean isAdicionado = Boolean.parseBoolean(adicionado);
            
      out.write("\r\n");
      out.write("            abrirPopupInformacoes(\"");
      out.print(isAdicionado ? "check.svg" : "wrong.svg");
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(isAdicionado ? "Registro adicionado!" : "Erro ao adicionar");
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(isAdicionado ? "O novo dado foi salvo com sucesso." : "Não foi possível salvar o registro. Tente novamente.");
      out.write("\")\r\n");
      out.write("        ");
 } else if (alterado != null) { 
      out.write("\r\n");
      out.write("            ");

                boolean isAlterado = Boolean.parseBoolean(alterado);
            
      out.write("\r\n");
      out.write("            abrirPopupInformacoes(\"");
      out.print(isAlterado ? "check.svg" : "wrong.svg");
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(isAlterado ? "Alteração concluída!" : "Erro ao editar");
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(isAlterado ? "O registro foi atualizado com sucesso." : "Não foi possível atualizar o registro.");
      out.write("\")\r\n");
      out.write("        ");
 } else if (deletado != null) { 
      out.write("\r\n");
      out.write("            ");

                boolean isDeletado = Boolean.parseBoolean(deletado);
            
      out.write("\r\n");
      out.write("            abrirPopupInformacoes(\"");
      out.print(isDeletado ? "check.svg" : "wrong.svg");
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(isDeletado? "Registro removido!" : "Erro ao excluir");
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(isDeletado ? "O dado foi excluído do sistema." : "Não foi possível remover o registro.");
      out.write("\")\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
